version: '3.1'

services:
  # lb:
  #   image: nginx:latest
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - urlshortener1
  #     - urlshortener2
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   networks:
  #     - loadbalancer

  # urlshortener1:
  #   image: shortener:dev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: dev-build
  #   environment: []
  #   volumes:
  #     - ./src:/app/src
  #   expose:
  #     - "3000"
  #   # ports:
  #   #   - "3000:3001"
  #   depends_on:
  #     - zoo1
  #     - cassandra
  #   command: ["npm", "run", "dev"]
  #   networks:
  #     - loadbalancer
  #     - dependencies

  # urlshortener2:
  #   image: shortener:dev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: dev-build
  #   environment: []
  #   volumes:
  #     - ./src:/app/src
  #   expose:
  #     - "3000"
  #   # ports:
  #   #   - "3000:3002"
  #   depends_on:
  #     - zoo1
  #     - cassandra
  #   command: ["npm", "run", "dev"]
  #   networks:
  #     - loadbalancer
  #     - dependencies

  # cache:
  #   image: redis:7.2
  #   hostname: redis
  #   restart: always
  #   ports :
  #     - 6379:7379
  #   networks:
  #     - dependencies

  urlshortener:
    image: shortener:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-build
    environment: []
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - zoo1
      - cassandra
    command: ["npm", "run", "dev"]
    networks:
      - dependencies

  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    # ports:
    #   - 2181:2181
    expose:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
    networks:
      - dependencies

  cassandra:
    image: cassandra:latest
    hostname: cassandra
    expose:
      - 9042:9042
    # ports:
      # - "7001:7001"
      # - 9042:9042
    networks:
      - dependencies

networks:
#   loadbalancer:
  dependencies:
